services:
  whatsapp-flows:
    build: .
    container_name: whatsapp-extremidade
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - proxy_public
      - shared_services
    environment:
      PORT: 3005

      PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDbI6x1ETTymagw\nsON4eF2N24OOBDT1AsqYg/DyAMjK3tN/RKjUOgcgZpFTHLVtcD/4GUjP2wz+NRDS\nEWKhwJWR3J+MvjJnWX7EI1M6NvyuJ3704p9O5uYQywDrJl5qJs4HuZiDxZ6fOcyU\nydo9oslzgyoiE4edE6bSa77L+6nXT1ec2E0Rps7PD5Kv2WTqRZCtemuqH9NiFPvc\nVf1rY9URogD4qt0J4kB07eOkoWe0Iv1rkUqOgELMp+tnLIO2lcOA9KC5X+x825yO\nKKOqnW2LX/KPpIJ4mUtYc6dTVksHKhpWZ77KXE/MQXa1darVhEtulPmrg58Iq1UU\nSSDba6wjAgMBAAECgf9DI5FD5k59OKes7fx/Bfs9YYPTKan+3n4zxJ84MI3czSPu\nOAFfrvAqsFMaPUKL5zYYgFFOkLS3LZwCN8jVkryEyT4Yxz4QfQ4d54GPw1oerAwx\nDAp+xC5SOxM3ownBr0QJ97lTlOuVZY7qj5gSBfiQYuwWyOT/dsolnMwk1Q+SAO/9\nhUoIqs5dk0/rJQx3HOtNsp6yu3HuSuwCFLuvwDsraxxUqJxyvkenm7s/Tw9K2DlW\n8aW8jnCeWZgmwHx5q19EzzC95A9Yzz0MD5kYdHXtO9IEjtJT6XYWd5QB2OXmnXki\nACGFDRUQ+1Jo20l+lZm+bUXPc2hOMxownxpi5lUCgYEA+hPep+jDq3nLA8JBYoLZ\notKfDnO03nnjopDVpr4nQ13v+C2EJuEam9OMU7/r0YJCu5S2F1nxaIfAC/2gOz7t\nm8Y0LzmNevsrUsSPNvAsNls/T4jq8aKx6ZCvJn/SLvRUYUGZmlflEAISpuJ+86xc\nknLdPcF5Z0Q7fs9oLn5cC6cCgYEA4FQ8g3jjAe8q2JqBKP6Or62KxxXvVKkTeZrp\n9G4T0kK2A/R8Tquz98IPB7cZxBp4aUZ6aarqwRwjxyVmFM8OmKUpWS31eHSD1n6/\nrs0zPECu5hhP52BLE3J8lzan/t4iStJqfls96ArRLPudgzTjvZHEvFY3a18DxqLp\nIR7tuyUCgYEAsWTQ5/kEfCocKeFtckzxxz9zFtRbNAnwwQvOksaGoZIMPNdEzDOY\nJXuOKoaU6HxnjBq0hKIHzielwpu6QuyjroGN2QYRZ3CuTbsjAEykgDaAFZJBXwET\nBWTd6gh391jYVlkrdcHtukpOItW+Smo1DKmwaTNKREexkIXeGEUIVDcCgYBUnlHJ\nQgNXSnE+DWHlJciK6gpsOJDzvWdUOqQ/iHo/mNxxt3pgbpJPRctHnMDCYT3EcEpi\nq48r0sKIL0pHVSdrWvmy4wwyKLlGYr9JX6wQ8VFICCmz3HXVWx02KO7Ly9zhnmd/\nTEmYyuPGdQ8gXAYADwlIBbmX7dpNxkvsK29/ZQKBgE9U3ihzfZ+QzHHTQPit4FH/\n5F++4S5wSojkQI/IRHVvWeDhlYUYbYWIMGnfhrbDXhJjoBtiQI1OQB10lxf6DnSS\nL1qW8HuGPVY3JKyjZ6mTRZAGM2qVWnXT+YYgTQTFHG1JI+P0m5vxlBtB95UEjb4L\n9WFu2V47GUjhxhZ+v3uD\n-----END PRIVATE KEY-----'

networks:
  proxy_public:
    external: true
  shared_services:
    external: true